Add basic ARC support
ivmai/libatomic_ops pull request #47
Opened 2020-08-25 22:10 UTC by vineetgarc

Basic support, verfied with make check on target

| /home/root/libatomic_ops>uname -a
| Linux hsdk 5.9.0-rc1-00006-g8f20d5e3b890 #132 SMP PREEMPT Tue Aug 25 14:33:13 PDT 2020 arc arc arc GNU/Linux
| /home/root/libatomic_ops>make check
| ...
| PASS: test_atomic
| PASS: test_atomic_generalized
| PASS: test_stack
| PASS: test_malloc
| PASS: test_atomic_pthreads
| ============================================================================
| Testsuite summary for libatomic_ops 7.7.0
| ============================================================================
| # TOTAL: 5
| # PASS:  5
| # SKIP:  0
| # XFAIL: 0
| # FAIL:  0
| # XPASS: 0
| # ERROR: 0
| ============================================================================
|

Signed-off-by: Vineet Gupta <vgupta@synopsys.com>

2020-08-26 06:50 UTC, ivmai requested changes
Hi. ARC is already supported by the following code. Why do we need this patch?

```
# else /* etc. */
#   include "atomic_ops/sysdeps/gcc/generic.h"
```

2020-08-26 14:21 UTC, vineetgarc commented
You are right, the generic fallback will work for any new arch, but adding it explicitly into build system allows for
1. Calling out that arch is supported/tested.
2. Enable future arch specific changes.

Anyways we can do that when need comes if you think that way.

Thx for taking a look.

2020-08-27 17:27 UTC, ivmai commented
> Enable future arch specific changes.
> Anyways we can do that when need comes if you think that way.

Right. E.g. adding double-word primitives support requires the change you did.

I'm closing the PR for now.

2020-08-27 17:27 UTC, closed without merging

2020-08-27 17:32 UTC, ivmai commented
BTW. I have removed gcc/nios2.h for the same reason - the arch is handled purely by gcc atomic primitives.